create database if not exists happy;
use happy;

CREATE TABLE  agent (
  AGENT_CODE varchar(6) not NULL ,
  AGENT_NAME varchar(40) not NULL,
  WORKING_AREA varchar(35) not NULL,
  COMMISSION decimal(10,2) not NULL,
  PHONE_NO varchar(15) not NULL,
  COUNTRY varchar(25) not NULL,
  SALARY INT not NULL,
  PRIMARY KEY (AGENT_CODE)
);
/* drop table agent;*/
 
INSERT INTO agent (AGENT_CODE, AGENT_NAME, WORKING_AREA, COMMISSION, PHONE_NO, COUNTRY,SALARY) VALUES
('A007  ','Ramasundar', 'Bangalore ', '0.15', '077-25814763', 'india','45545'),
('A003  ', 'Alex ', 'London', '0.13', '075-12458969', 'UK','39000'),
('A008  ', 'Alford', 'New York ', '0.12', '044-25874365', 'USA','45000'),
('A011  ', 'Ravi Kumar', 'Bangalore ', '0.15', '077-45625874', 'IND','50000'),
('A010  ', 'Santakumar ', 'Chennai', '0.14', '007-22388644', 'IND','50000'),
('A012  ', 'Lucida', 'San Jose ', '0.12', '044-52981425', 'USA','41000'),
('A005  ', 'Anderson', 'Brisban', '0.13', '045-21447739', 'UK','98500'),
('A001  ', 'Subbarao', 'Bangalore', '0.14', '077-12346674', 'IND','65500'),
('A002  ', 'Mukesh', 'Mumbai', '0.11', '029-12358964', 'CHI','65500'),
('A006  ', 'McDen ', 'London', '0.15', '078-22255588 ', 'NZ','89000'),
('A004  ', 'Ivan', 'Torento', '0.15', '008-22544166', 'AUS','15000'),
('A009  ', 'Benjamin', 'Hampshair', '0.11', '008-22536178 ', 'GER','15000');

select * from agent;

CREATE TABLE company (
  COMPANY_ID varchar(6) not NULL ,
  AGENT_CODE varchar (25) not NULL,
  COMPANY_NAME varchar(25) not NULL,
  COMPANY_CITY varchar(25) not NULL,
  TURNOVER int not NULL,
  SHARE decimal(10,2)  not NULL,
  SALARY INT not  NULL,
  PRIMARY KEY (COMPANY_ID)
);


INSERT INTO company (COMPANY_ID,AGENT_CODE, COMPANY_NAME, COMPANY_CITY,TURNOVER, SHARE,SALARY) VALUES
('18','A002', 'Order All', 'Boston','5000','18.2','45000'),
('15','A006', 'Jack Hill Ltd', 'London','8500','14.5','49580'),
('16','A003', 'Akas Foods', 'Delhi','4500','11.2','45000'),
('17', 'A001','Foodies.', 'London','9000','17.2','36800'),
('19', 'A004','sip-n-Bite.', 'New York','10000','13.9','11200'),
('21', 'A008','MCD.', 'New York','45000','10.2','11200'),
('11', 'A005','CCD', 'Mumbai','46500','8.2','12300')
;

SELECT * FROM company;
SELECT * FROM agent;

SELECT DISTINCT COMPANY_CITY
FROM COMPANY;

SELECT  COMPANY_NAME FROM COMPANY;

SELECT COUNT(DISTINCT COUNTRY) FROM agent;

/*
SELECT Count (*) AS DistinctCountries
FROM (SELECT DISTINCT COUNTRY FROM agent);  
*/

/* WHERE */
SELECT * FROM agent
WHERE COUNTRY='IND';

SELECT * FROM agent
WHERE AGENT_CODE='A010';

SELECT * FROM company
WHERE company_id =11;


/*WHERE with AND OR NOT */

SELECT * FROM agent
WHERE COUNTRY='IND' AND WORKING_AREA='Bangalore';

SELECT * FROM agent
WHERE COMMISSION =0.15 OR COUNTRY='UK';

SELECT * FROM agent
WHERE COUNTRY='GER' OR COUNTRY='USA';

SELECT * FROM agent
WHERE NOT COUNTRY='IND';

SELECT * FROM agent
WHERE COUNTRY='IND' AND (WORKING_AREA='Chennai' OR WORKING_AREA='Bangalore');

SELECT * FROM agent
WHERE NOT COUNTRY='IND' AND NOT Country='USA';

/* ORDER BY */

SELECT * FROM agent
ORDER BY COUNTRY;

SELECT * FROM agent
ORDER BY COUNTRY DESC;

SELECT * FROM agent
ORDER BY  COUNTRY,AGENT_NAME;  /* This means that it orders by Country, but if some rows have the same Country, it orders them by Agent name*/

/* UPDATION of some row*/
update agent set COUNTRY='IND' where AGENT_NAME ='Ramasundar';

/* SELECT * FROM agent
ORDER BY COUNTRY DESC , AGENT_NAME ASC; */

/* IS NULL , IS NOT NULL*/
SELECT AGENT_NAME, COMMISSION
FROM agent
WHERE COMMISSION IS NULL;

SELECT AGENT_NAME, COMMISSION
FROM agent
WHERE COMMISSION IS NOT NULL;

/* DELET EXAMPLES*/

DELETE FROM agent WHERE AGENT_NAME ='Alfreds Futterkiste'; /*DONT DELET*/
DELETE FROM table_name;
DELETE FROM COLUMN_NAME;

/* TOP STATEMNETS*/

SELECT * from agent
limit 3;

/*min max*/

SELECT MIN(SALARY) AS SmallestPrice
FROM agent;

SELECT MAX(SALARY) AS SmallestPrice
FROM agent;

/* count avg sum*/
SELECT COUNT(AGENT_CODE)
FROM AGENT;

SELECT AVG(COMMISSION)
FROM AGENT;

SELECT COUNT(COUNTRY)
FROM AGENT;

/*LIKE WILDCARD*/

SELECT * FROM AGENT
WHERE AGENT_NAME  not LIKE 'a%o';

SELECT * FROM AGENT
WHERE WORKING_AREA LIKE '%E';
 
 /*WILDCARD*/
SELECT * FROM AGENT
WHERE WORKING_AREA NOT LIKE '[bsp]%';

SELECT * FROM AGENT
WHERE WORKING_AREA LIKE '[a-c]%';

/*IN*/
SELECT * FROM AGENT
WHERE WORKING_AREA IN ('CHENNAI');

SELECT * FROM AGENT
WHERE SALARY IN (SELECT SALARY FROM company);

SELECT * FROM AGENT
WHERE COMMISSION  BETWEEN 0.12 AND 0.14;

SELECT * FROM AGENT
WHERE COMMISSION NOT BETWEEN 0.12 AND 0.14;


SELECT * FROM AGENT
WHERE COMMISSION  BETWEEN 0.12 AND 0.14
AND AGENT_CODE NOT IN ('A001','A003');

/* ALIASES   */

SELECT  COMPANY.COMPANY_NAME,COMPANY.TURNOVER,AGENT.SALARY
FROM AGENT, COMPANY
WHERE AGENT.AGENT_NAME='Subbarao' and AGENT.AGENT_CODE=COMPANY.AGENT_CODE;

SELECT  COMPANY.COMPANY_NAME,COMPANY.TURNOVER,AGENT.SALARY
FROM AGENT, COMPANY
WHERE AGENT.AGENT_NAME='Subbarao' or AGENT.AGENT_CODE=COMPANY.AGENT_CODE;

SELECT * FROM AGENT;
SELECT * FROM COMPANY;



/* JOINS*/

SELECT AGENT.AGENT_NAME, COMPANY.COMPANY_Name, AGENT.COMMISSION
FROM AGENT
INNER JOIN COMPANY ON AGENT.AGENT_CODE=COMPANY.AGENT_CODE;

SELECT AGENT.AGENT_NAME, COMPANY.COMPANY_Name, AGENT.COMMISSION
FROM AGENT
FULL  JOIN COMPANY ON AGENT.AGENT_CODE=COMPANY.AGENT_CODE;

SELECT AGENT.AGENT_NAME, COMPANY.COMPANY_Name, AGENT.COMMISSION,AGENT.AGENT_CODE
FROM agent
LEFT JOIN company ON AGENT.AGENT_CODE=COMPANY.AGENT_CODE
ORDER BY AGENT.AGENT_CODE;

SELECT * FROM AGENT;
SELECT * FROM COMPANY;

SELECT AGENT.AGENT_NAME, COMPANY.COMPANY_Name, AGENT.COMMISSION,COMPANY.AGENT_CODE
FROM AGENT
RIGHT JOIN COMPANY ON AGENT.SALARY=COMPANY.SALARY
ORDER BY AGENT.AGENT_NAME;

SELECT * FROM AGENT;
SELECT * FROM COMPANY;

 /* UNION */

SELECT AGENT_CODE FROM COMPANY
UNION
SELECT AGENT_CODE FROM AGENT
ORDER BY AGENT_CODE;

SELECT AGENT_CODE FROM COMPANY
UNION ALL
SELECT AGENT_CODE FROM AGENT
ORDER BY AGENT_CODE;

SELECT AGENT_CODE, SALARY FROM AGENT
WHERE COUNTRY ='IND'
UNION
SELECT AGENT_CODE, SALARY FROM COMPANY
WHERE COMPANY_CITY='London'
ORDER BY AGENT_CODE;

SELECT AGENT_CODE, SALARY FROM AGENT
WHERE SALARY =45000
UNION 
SELECT AGENT_CODE, SALARY FROM COMPANY
WHERE SALARY =45000
ORDER BY AGENT_CODE;

SELECT * FROM AGENT;
SELECT * FROM COMPANY;

 /* GROUP BY*/

SELECT COUNT(COMMISSION), COUNTRY
FROM agent
GROUP BY COUNTRY;

SELECT COUNT(COMMISSION), COUNTRY
FROM agent
GROUP BY COUNTRY
ORDER BY COUNT(COMMISSION) DESC; /* OR  ORDER BY COUNTRY;*/

/*GROUP BY WITH JOIN*/
SELECT AGENT.AGENT_NAME, COUNT(COMPANY.SALARY) AS NumberOf_SALLARIED_PERSONS
FROM agent
LEFT JOIN COMPANY  ON AGENT.SALARY=COMPANY.SALARY
GROUP BY AGENT_NAME;

SELECT AGENT.WORKING_AREA, COUNT(COMPANY.COMPANY_CITY) AS NumberOf_SALLARIED_PERSONS
FROM agent
RIGHT JOIN COMPANY  ON AGENT.AGENT_CODE=COMPANY.AGENT_CODE
GROUP BY WORKING_AREA;

SELECT * FROM AGENT;
SELECT * FROM COMPANY;

/*HAVING CLAUSE*/
/*
SELECT COUNT(PHONE_NO), COUNTRY 
FROM agent
GROUP BY COUNTRY
HAVING COUNT(COUNTRY) > 0;
SELECT * FROM AGENT */

/* exist*/
SELECT *
FROM agent
WHERE EXISTS (SELECT *
FROM Company
WHERE agent.AGENT_CODE = COMPANY.AGENT_CODE AND SALARY >40000);


SELECT *
FROM agent
WHERE EXISTS (SELECT *
FROM Company
WHERE agent.AGENT_CODE = COMPANY.AGENT_CODE AND SALARY =12300);
SELECT * FROM AGENT;
SELECT * FROM COMPANY;
 
 /* ANY ALL*/

SELECT *
FROM agent
WHERE AGENT_CODE = ANY
  (SELECT SHARE
  FROM company
  WHERE TURNOVER = 9000);

/*SELECT ALL ProductName
FROM Products
WHERE TRUE;*/

SELECT AGENT_NAME
FROM agent
WHERE COMMISSION = ALL
  (SELECT WORKING_AREA
  FROM company
  WHERE TURNOVER >00);
/* <> MEANS NOT EQUAL TO  */
select * from agent
where WORKING_AREA <> 'London';

select * from company
where COMPANY_CITY!= 'London';

SELECT * FROM COMPANY 
WHERE SALARY >25000 AND SALARY <50000;

SELECT * FROM(SELECT * FROM agent order by  salary  ) AS RD_HIGH 
ORDER BY SALARY  ;  

WITH company AS
(
SELECT *, ROW_NUMBER() OVER
(ORDER BY AGENT_CODE) AS rn from agent
)
select * from company where rn % 2 = 1;

select * from company where COMPANY_ID % 2 = 1;